#api call for listing all employees

###
GET http://127.0.0.1:8000/employees/
Accept: application/json

#api call for create an employee

###
POST http://127.0.0.1:8000/employees/
Content-Type: application/json

{
  "name":"muhasina",
  "department":"sales",
  "salary":30000,
  "location":"thrissur",
  "email":"muhasina@gmail.com"
}

#api call for retrieve an employee

###
GET http://127.0.0.1:8000/employees/1/
Accept: application/json