#api call for listing all books

###
GET http://127.0.0.1:8000/books/
Accept: application/json

#api call for create a book

###
POST http://127.0.0.1:8000/books/
Content-Type: application/json

{
  "title":"Life of Pie",
  "author":"Yann Martel",
  "price":450,
  "pages":670,
  "publications":"H&C Publications"
}

#api call for retrieve a book

###
GET http://127.0.0.1:8000/books/2/
Accept: application/json

#api call for delete a book

###
DELETE http://127.0.0.1:8000/books/5/
Accept: application/json